spring:
  application:
    name: stock-service
  rabbitmq:
    exchange:
      name: order-exchange
    queue:
      name: stock-queue
    routing:
      key: stock-routing-key
    reply-to-queue:
      name: reply-to-queue