server:
  port: 8081
spring:
  application:
    name: order-service
  rabbitmq:
    queue:
      name: stock-queue
    topicExchange:
      name: order-exchange
    routing:
      key: stock-routing-key
    email:
      name: email-queue
    email-routing:
      key: email-routing-key
    reply-to-queue:
      name: reply-to-queue
    reply-routing:
      key: reply-routing-key
